apiVersion: v1
kind: Secret
metadata:
  name: yellowbooks-secrets
  namespace: yellowbooks
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_USER: eWVsbG93Ym9va3NfdXNlcg==
  DATABASE_PASSWORD: WWVsbG93Qm9va3MyMDI0IVNlY3VyZQ==
  
  # Prisma database URL
  DATABASE_URL: cG9zdGdyZXNxbDovL3llbGxvd2Jvb2tzX3VzZXI6WWVsbG93Qm9va3MyMDI0IVNlY3VyZUBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIveWVsbG93Ym9va3M=
  
  # NextAuth Configuration
  NEXTAUTH_URL: aHR0cHM6Ly9zaGFybm9tLnN5c3RlbXM6MzE1Mjk=
  NEXTAUTH_SECRET: a28zY1RUdlRCUWtMcFFvRU94N01jZnUxQU85cE5yUDk=
  
  # GitHub OAuth
  GITHUB_ID: T3YyM2xpQ01vR2VBbExZMGhqTUI=
  GITHUB_SECRET: YjlkZTY5NGVmNmMwY2Q1YzZkZGMyNjA0NGFlZDY1ODAzNTRiMzdjYg==
  
  # Frontend URL for CORS
  FRONTEND_URL: aHR0cHM6Ly9zaGFybm9tLnN5c3RlbXM6MzE1Mjk=
  
  # Lab 8: OpenAI and Redis Configuration (base64 encoded to avoid GitHub push protection)
  OPENAI_API_KEY: c2stcHJvai1pNTFTYTJtdEhEVldNU3l5LVFob0kxa25vQ3RfVmZIQndXSnVWQ1dTcmtOR0pMSWkxaHhrTkxETFR0M0ZYV3VadFVJVUlQcHVMdFQzQmxia0ZKY2NScFUtWmZ2ZENDSkZZLXZWNFhiU0xNcVRKdENaYTRmTGU5bnhCVnl5dmF3bGVtUm9nQmgyd3g1bjYxZlpsREtHeVJMOF9GVUE=
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
